In [ ]:
string="abcdefgh"
print("length= "+ str(len(string)))
string[0]

print("substring="+string[0:4])
print("substring 4th char onwards="+string[4:])
print("skice last 2 char="+string[:-2])
print("replace substring="+string.replace('f','0'))
print("replace substring="+string.replace('f','0').replace('0','f'))

In [ ]:
#tuples are sequence of imutable python object
weeks=("sunday","monday","tuesday","wednessday","thursday","friday","saturday")
type(weeks)
print(weeks[0])
weeks[6]="test"

In [ ]:
#list are sequence of mutable python object
salaries=[10000,15000,20000]
type(salaries)
salaries[0]=18000
salaries
salaries[0]=salaries[0]+100
salaries[0]+=100
salaries.append(28000)
salaries
mixed=[1,'a',1.5]
mixed=[1,'a',1.5,[155,'b']]
mixed=[1,'a',1.5,(155,'b')]
mixed

In [ ]:
#Dictionarys are hash tables
#advantage over list is it allows to create in key value pair
salaries={"John":1500,"Jane":1400,"johny":500}
type(salaries)
salaries['Jane']#may give index error 
salaries.get("John",100)
salaries.get("Harry",500)


In [ ]:
#Sets are unorder collection of mutable objects of unique values, not duplicate values
s={}
type(s)
s=set()
type(s)
s.add(1)
s.add(2)
s.add(1)
s
1 in s



In [ ]:
x=20
if x<20:
    print("x less then 20")
    if x<15:
        print("x is less than 15")
    else:
        print("x is greater than 15")
elif x==20:
    print("x is equal to 20")
else:
    print("x is greater than 20")


In [ ]:
a=10
while a!=0:
    print(a)
    a-=1

In [53]:
for x in range(0,10):
    print(x,end=", ")

0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 

In [54]:
def downloadfile(url):
    print("establish connection "+url)
    print("open connection")
    print("download data")
    print("log to DB "+url)
    print("close connection")

downloadfile("ftp://www.abc.org")

def multiply(x,y):
    return x*y

print(multiply(10,45))

#lambda expression 
multyple=lambda x,y:x*y

print(multyple(5,6))

def createMultiplier(x):
    return lambda y:x*y

multi=createMultiplier(10)
print(multi(5))

establish connection ftp://www.abc.org
open connection
download data
log to DB ftp://www.abc.org
close connection
450
30
50


In [55]:
f = open("sample.txt",'x')
f.close()

FileExistsError: [Errno 17] File exists: 'sample.txt'

In [56]:
with open("sample.txt",'w') as f:
    f.write("sample line \nsample line")

In [57]:
with open("sample.txt",'a') as f:
    f.write("sample line \n")

In [58]:
with open("sample.txt",'r') as f:
    for l in f.readlines():print(l,end="")

x = range(10) 
y = sum(x)
print(y)



sample line 
sample linesample line 


TypeError: 'int' object is not callable

importing numpy

In [64]:
#pip install numpy

import numpy as np
#1D array
a=np.array([1,2,3])
print(a)

#2D array
b=np.array([[1,2,3],[4,5,6]])
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [69]:
np.arange(1,10,2)

np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [73]:
#filling RANDOM numbers in array of dimension x X y
np.random.random((2,3))

array([[0.25766487, 0.22883183, 0.47420441],
       [0.33739127, 0.75215659, 0.49882726]])

In [75]:
np.sum([10,20])

30

In [77]:
np.sum([[1,2],[5,6]],axis=0)

array([6, 8])

In [78]:
np.sum([[1,2],[5,6]],axis=1)

array([ 3, 11])

In [87]:
#subtracting two num
np.subtract(10,15)

#muliplying two num
np.multiply(2,3)

#dividing two num
np.divide(10,5)

#diving tow arrys
a=np.array([2,4,6])
b=np.array([1,2,3])
np.divide(a,b)

#exp, sqrt, sin, cos, log
print("Exponent : ",np.exp(a))
print("Square root : ",np.sqrt(a))
print("Sin : ",np.sin(a))
print("Cos : ",np.cos(a))
print("Log : ",np.log(a))

Exponent :  [  7.3890561   54.59815003 403.42879349]
Square root :  [1.41421356 2.         2.44948974]
Sin :  [ 0.90929743 -0.7568025  -0.2794155 ]
Cos :  [-0.41614684 -0.65364362  0.96017029]
Log :  [0.69314718 1.38629436 1.79175947]


In [89]:
#concept of broad casting..
import numpy as np
a = np.array([[0,0,0],[1,2,3],[4,5,6],[5,6,7]])
b = np.array([[0,1,2]])

print("First Array: \n",a,'\n')
print("Second Array: \n",b,'\n')
print("First Array + Second Array: \n",a+b,'\n')



First Array: 
 [[0 0 0]
 [1 2 3]
 [4 5 6]
 [5 6 7]] 

Second Array: 
 [[0 1 2]] 

First Array + Second Array: 
 [[0 1 2]
 [1 3 5]
 [4 6 8]
 [5 7 9]] 



In [95]:
a = [1,2,3,4,5] 
b = [6,7,8,9]

a.append(b)

print(a)

[1, 2, 3, 4, 5, [6, 7, 8, 9]]


In [101]:
def fun(x): 
    x[0] = 5 
    return x

g = [10,11,12]

print(fun(g))

tup = (1, 2, 3, 4, 5 ) 

[5, 11, 12]


In [8]:
import time

X=range(100)
t1=time.time()
print(t1)

1715853253.6161554
